const songs = [
    "1,2,3,4!.mp3",
    "A Bella!.mp3",
    "Abnormality Dancin' Girl [ENGLISH COVER].mp3",
    "Abnormality Dancin' Girl.mp3",
    "Affection Addiction.mp3",
    "ALTERED OBSIDIAN.mp3",
    "Amulet.mp3",
    "another end.mp3",
    "Avantgarde.mp3",
    "Between Two Worlds.mp3",
    "BIRDBRAIN.mp3",
    "BROWN SUGAR RUSH!.mp3",
    "Bubble.mp3",
    "BUTCHER VANITY.mp3",
    "Capsule Dreamer.mp3",
    "CHAOS CONSTRUCT.mp3",
    "Chaos Control.mp3",
    "Compass.mp3",
    "Crowning End.mp3",
    "De Kieru.mp3",
    "Fluquor.mp3",
    "Fly, My Wings.mp3",
    "GLOW UP ERA.mp3",
    "GOODNIGHTSWEETANGEL.mp3",
    "Grievous Lady -nothing is but what is not-.mp3",
    "Hero.mp3",
    "How To Make A Music Game Song!.mp3",
    "I don't know what i made but it sounds good to me soooo.mp3",
    "I Love Hanging Outside.mp3",
    "I'm Sorry I'm a Monster.mp3",
    "I'm Talking To You! [ENGLISH VER].mp3",
    "I'm Talking To You!.mp3",
    "IGAKU (Medicine).mp3",
    "In Hell We Live, Lament.mp3",
    "In The Blue Of Twilight☆Sky～.mp3",
    "Inflamer.mp3",
    "IT DOESN'T END HERE.mp3",
    "Last Resort.mp3",
    "LOOKING GLASS LUMINESCENCE.mp3",
    "Looping The Rooms.mp3",
    "Magnolia.mp3",
    "MAKE THE SKY FALL.mp3",
    "Marigold.mp3",
    "MECHANICAL GOD.mp3",
    "Medianoche.mp3",
    "Miko Skip.mp3",
    "Mugikamagika.mp3",
    "Myosotis.mp3",
    "Orbital Love Strike.mp3",
    "Overclocked.mp3",
    "Penumbra Phantasm.mp3",
    "Puppet.mp3",
    "Purgatorium.mp3",
    "Quo Vadis.mp3",
    "Release Cut Piano.mp3",
    "Retry Now.mp3",
    "Russian Roulette.mp3",
    "Spoken For.mp3",
    "Static.mp3",
    "String Theocracy.mp3",
    "Sugar Rush.mp3",
    "Super Limit Buster.mp3",
    "Through Patches of Violet.mp3",
    "To Feel Alive.mp3",
    "Traitor.mp3",
    "Transparent'n'false.mp3",
    "Underdog.mp3",
    "Underworld Steam Quality Savory Function Egg Festival.mp3",
    "Violence, Execution.mp3",
    "weathergirl.mp3",
    "world.execute(me);.mp3",
    "You've Got Mail!.mp3"
]