const songs = [
    "'YARARARA'.mp3",
    "1,2,3,4!.mp3",
    "A Bella!.mp3",
    "Abnormality Dancin' Girl (English Cover).mp3",
    "Abnormality Dancin' Girl.mp3",
    "Affection Addiction.mp3",
    "Akaboshi Mizeraburu ~Haiokuhen.mp3",
    "ALTERED OBSIDIAN.mp3",
    "Amulet.mp3",
    "ANiMA.mp3",
    "another end.mp3",
    "Applause.mp3",
    "Avantgarde.mp3",
    "Bad Apple!!.mp3",
    "Between Two Worlds.mp3",
    "BIRDBRAIN.mp3",
    "BROWN SUGAR RUSH!.mp3",
    "Bubble.mp3",
    "BUTCHER VANITY.mp3",
    "Capsule Dreamer.mp3",
    "CHAOS CONSTRUCT.mp3",
    "Chaos Control.mp3",
    "Cirno's Perfect Math Class.mp3",
    "Compass.mp3",
    "Crowning End.mp3",
    "Cutie Mew Mew Magic.mp3",
    "De Kieru.mp3",
    "deltaTime.mp3",
    "dig in.mp3",
    "Displayholic.mp3",
    "Ego Renegade Boy.mp3",
    "Exodus.mp3",
    "Exorcist.mp3",
    "Flower Man.mp3",
    "Fluquor.mp3",
    "Fly, My Wings.mp3",
    "GAMBLER'S FALLACY.mp3",
    "GLOW UP ERA.mp3",
    "GOODNIGHTSWEETANGEL.mp3",
    "Grievous Lady -nothing is but what is not-.mp3",
    "Heart in Wonderland.mp3",
    "Help me, ERINNNNNN!!.mp3",
    "Hero.mp3",
    "How To Make A Music Game Song!.mp3",
    "I don't know what i made but it sounds good to me soooo.mp3",
    "I Love Hanging Outside.mp3",
    "I Need You.mp3",
    "I Should Kill Myself.mp3",
    "I'm Sorry I'm a Monster.mp3",
    "I'm Talking To You! (English Cover).mp3",
    "IGAKU (Medicine).mp3",
    "In Hell We Live, Lament.mp3",
    "In The Blue Of Twilight☆Sky～.mp3",
    "Inflamer.mp3",
    "IT DOESN'T END HERE.mp3",
    "kisaragi.mp3",
    "Konton Boogie (English Cover).mp3",
    "Kyu-kukarin.mp3",
    "Last Brutal Sister Flandre S.mp3",
    "Last Resort.mp3",
    "LOOKING GLASS LUMINESCENCE.mp3",
    "Looping The Rooms.mp3",
    "Love-colored Master Spark.mp3",
    "Magnolia.mp3",
    "MAKE THE SKY FALL.mp3",
    "Marigold.mp3",
    "Matsuyoi Nightbug.mp3",
    "MECHANICAL GOD.mp3",
    "Medianoche.mp3",
    "Mesmerizer.mp3",
    "Miko Skip.mp3",
    "Mischievous Sensation.mp3",
    "Mu Sekinin Shuugoutai.mp3",
    "Mugikamagika.mp3",
    "My Bread was Burnt to a Crisp.mp3",
    "My Dear, Deemo.mp3",
    "Myosotis.mp3",
    "Night of Nights.mp3",
    "NO CONTROL.mp3",
    "NOT A CAT.mp3",
    "Orbital Love Strike.mp3",
    "Overclocked.mp3",
    "Override (English Cover).mp3",
    "Penumbra Phantasm.mp3",
    "People People.mp3",
    "Petal Phantasm.mp3",
    "Primrose.mp3",
    "Puppet.mp3",
    "Purgatorium.mp3",
    "Quo Vadis.mp3",
    "Rabbit Hole.mp3",
    "Release Cut Piano.mp3",
    "Rendezvous.mp3",
    "Retry Now.mp3",
    "Romeo and Cinderella.mp3",
    "Run Go Run.mp3",
    "Ruru's Suicide Show on a Livestream.mp3",
    "Russian Roulette.mp3",
    "SAIKAI.mp3",
    "Scarlet Police on Ghetto Patrol.mp3",
    "selfish you.mp3",
    "sink to the deep sea world.mp3",
    "Spoken For.mp3",
    "Squeaky Mind.mp3",
    "Static.mp3",
    "streetcat.mp3",
    "String Theocracy.mp3",
    "Sugar Rush.mp3",
    "sunspotter.mp3",
    "Super Limit Buster.mp3",
    "Telecaster B-Boy (English Cover).mp3",
    "The Maid's Heart is a Puppet.mp3",
    "Through Patches of Violet.mp3",
    "TIAN TIAN.mp3",
    "To Feel Alive.mp3",
    "Traitor.mp3",
    "Transparent'n'false.mp3",
    "U.N. Owen Was Her.mp3",
    "Underdog.mp3",
    "Underworld Steam Quality Savory Function Egg Festival.mp3",
    "Uso to Doukoku.mp3",
    "Ussewa (English Cover).mp3",
    "Violence, Execution.mp3",
    "weathergirl.mp3",
    "world.execute(me);.mp3",
    "Xing-Lai Heaven.mp3",
    "You've Got Mail!.mp3",
    "Your Monster.mp3",
    "Zako.mp3",
    "▪︎.mp3",
    "炜WARD ROMANCE.mp3"
]